# Generated by Django 2.0.7 on 2018-07-05 15:57
# -*- coding:utf8 -*-
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='title')),
            ],
            options={
                'verbose_name_plural': '书',
                'verbose_name': '书',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='名称')),
                ('address', models.CharField(max_length=128, verbose_name='地址')),
            ],
            options={
                'verbose_name_plural': '出版社',
                'verbose_name': '出版社',
            },
        ),
        migrations.AddField(
            model_name='books',
            name='publisher',
            field=models.ForeignKey(on_delete=True, to='app01.Publisher'),
        ),
    ]
