# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-07-03 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.CharField(max_length=32, verbose_name='\u540d\u79f0'),
        ),
    ]
